name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Kaitai and other depedencies
      run: |
        sudo apt-key adv --no-tty --keyserver hkp://pool.sks-keyservers.net --recv 379CE192D401AB61
        echo "deb https://dl.bintray.com/kaitai-io/debian jessie main" | sudo tee /etc/apt/sources.list.d/kaitai.list
        sudo apt-get update
        sudo apt-get install kaitai-struct-compiler python3-setuptools
    - name: Prepare test
      run:  cd tests/ && pip3 install -r requirements.txt
    - name: Run test
      run: cd tests/ && ./run.sh
